# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dae046563909f0b72239049051d3c48e8b6f8b2b519ea9ab969af66788344d8a8dc8f43c488650d637bb08c2b01d766ab012729a1f56ddf050d17c6f8f76f0ab

test:
  secret_key_base: 0e784e458086e676581ddd84c6f79522e9308394659be05feb3376f9a62bc21eb6682e3a16b9e7019fb9701b163941ab987574e67e181f15b28590669b196df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
